### PR TITLE
Allow paste via mouse to work

### PR DESCRIPTION
**Pull request by codeodor**
Fixes this issue:

Cannot paste via mouse

### CODE REVIEW

**Comment by codeodor** [comment]
Just to be clear, what happens is:

1. Paste via mouse puts the value into the field
2. When the field loses focus, it changes back to the pre-pasted value.

This fixes that so that the pasted value stays.

**Comment by codeodor** [comment]
I ran grunt against it, fixed the error, and rebased with the `dist`changes in the commit.

**Comment by mjolnic** [comment]
@codeodor thanks for the contribution!

**Comment by codeodor** [comment]
My pleasure! :+1:

**Pull request merged**
