### PR TITLE
Bootstrap Colorpicker 3.0 (WIP)

### PR DESCRIPTION
**Pull request by mjolnic**
The next major release will be only compatible with Bootstrap 3.x and ECMAScript 5 browsers.
It will integrate new features like palettes (with some useful predefined) and the fantastic
TinyColor plugin that have a powerful color parser and generator. Take a look at the `tinycolor`
branch.

## Features

* [TinyColor](https://github.com/bgrins/TinyColor) integration
* Bootstrap Popover compatibility
* No external background images are required (all UI use gradients for resize support)
* Fully customizable LESS file
* Palettes, with some useful predefined ones (triad', tetrad, monochromatic, analogous, complementary,
  lightness, lighten, darken, brighten, saturate, desaturate, mixed, or your custom colors array)
* More reliable: v2 uses a 100px areas which cause some colors not to be selectable with enough precision, v3 uses 256px (the large version is a 65536 colors matrix, like photoshop) or 128px by default.

## TO-DO
Re adapt v2 api:
- [x] integrate [bootstrap-popover-picker](https://github.com/mjolnic/bootstrap-popover-picker) API
- [x] Mouse events
- [ ] Input events / behaviours
- [x] Picker events
- [ ] Inline mode
- [ ] Vertical mode
- [ ] Component mode
- [x] Arrow position as an option
- [ ] Resolve opened issues for v2

## Other ideas
- [ ] Optional alpha bar? This may cause width issues with palettes.
- [ ] Vertical palette? Ability to replace the alpha bar with a palette?
- [ ] Implement optional ok/cancel buttons? This would be placed in the bottom as an horz. bar.
- [ ] Implement optional color preview (current/new)? (In the same bar as ok/cancel)

## Preview

Here is a screenschot of the WIP development of Bootrstrap Colorpicker 3 ;)

bootstrap-colorpicker 3 preview

This pull request is related to #78

### CODE REVIEW

**Comment by esbanarango** [comment]
Any plans on merging this?

**Comment by mjolnic** [comment]
@esbanarango hi, not yet, cause it has a lot of problems yet as you can see if you clone the branch.

**Comment by sergiopantoja** [comment]
:+1: Looking forward to it! Thanks for your work on this

**Comment by mjolnic** [comment]
Closing this in favor of `develop` branch. Some of the concepts here explained will be integrated there, but with less drastical changes.

https://github.com/mjolnic/bootstrap-colorpicker/tree/develop

**Pull request closed without merging**
